FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Dépendances backend
COPY elearning/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Copier le code backend + le package learning_platform
COPY elearning/ /app/
COPY learning_platform/ /app/learning_platform/

# Pour que Python voie /app et donc le package learning_platform
ENV PYTHONPATH=/app

# (option) healthcheck si /health existe
# HEALTHCHECK --interval=30s --timeout=5s --retries=3 CMD curl -fsS http://localhost:5000/health || exit 1

# Important : ton app est dans elearning/api/app.py → module = api.app:app
CMD ["gunicorn","-w","2","-k","gthread","-b","0.0.0.0:5000","api.app:app"]
