FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# 1) Dépendances backend
COPY elearning/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt \
    && pip install --no-cache-dir "gunicorn>=21.2"

# 2) Code backend + librairie learning_platform (copie des 2 dossiers)
COPY elearning/ /app/
COPY learning_platform/ /app/learning_platform/

# 3) Assure que /app est dans le chemin d'import
ENV PYTHONPATH=/app

# 4) Démarrage : ton app est dans elearning/api/app.py -> objet "app"
CMD ["gunicorn","-w","2","-k","gthread","-b","0.0.0.0:5000","api.app:app"]
