# Generated by Django 5.2.2 on 2025-08-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20250521_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
